[theme]
base = "light"
primaryColor = "#1668E3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f5"
textColor = "#222222"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
